### ISSUE TITLE
Empty unit configs are sometimes transmitted and only forwarded to the authentication lib

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#61]
I have no idea what the purpose of such messages is but sometimes (2-3 times per mock registry startup) there are empty unit configs transmitted (only containing a permission config) during the user registration. I just detected this strange behaviour during refactoring of the authentication helper. 

Code applied to catch the empty message
<pre>
                // ticket no available so request without login
                try {
                    // when not logged in the received value is not encrypted but just send as a byte string
                    // so get the received message by calling parseFrom which is supported by every message
                    Method parseFrom = internalClass.getMethod("parseFrom", ByteString.class);
                    RECEIVE message = (RECEIVE) parseFrom.invoke(null, authenticatedValue.getValue());

                    // retrieve the unit config which is used to check for permissions 
                    UnitConfig unitConfig = configRetrieval.retrieve(message);

                    if (unitConfig.getType() == UnitType.UNKNOWN) {
                        throw new InvalidStateException("Unit type of received unit config is unknown! Reject request because message seems to be broken.");
                    }
</pre>

Any Idea of the purpose?

How to reproduce:
* checkout all bco master branches
* checkout branch ''bugfix-unknown-unit-message'' of the bco.authentication
* build all components 
* execute the registry test

<pre>
21:33:56.892 [pool-1-thread-100] INFO  o.o.b.r.m.MockRegistry Register user...
21:33:56.904 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUnitConfigAuthenticated(AuthenticatedValue)] of UnitRegistryController[/test/divine/registry/unit/status/]!
21:33:56.904 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController  ╚══╦═⚀ Could not invoke Method[Class registerUnitConfigAuthenticated(AuthenticatedValue)] of UnitRegistryController[/test/divine/registry/unit/status/]!
21:33:56.905 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController     ╚══╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not execute authenticated action
21:33:56.905 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController        ╚══╦═⚀ Could not execute authenticated action
21:33:56.905 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController           ╚════⚀ Unit type of received message is unknown! Reject actions because the config seems to be broken.
21:33:56.905 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController =====================================
21:33:56.908 [Thread-158] ERROR o.o.b.r.u.c.UnitRegistryController org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUnitConfigAuthenticated(AuthenticatedValue)] of UnitRegistryController[/test/divine/registry/unit/status/]!
rsb.patterns.Callback$UserCodeException: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUnitConfigAuthenticated(AuthenticatedValue)] of UnitRegistryController[/test/divine/registry/unit/status/]!
	at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:120)
	at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUnitConfigAuthenticated(AuthenticatedValue)] of UnitRegistryController[/test/divine/registry/unit/status/]!
	... 3 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not execute authenticated action
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:96)
	... 2 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not execute authenticated action
	at org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:146)
	at org.openbase.bco.registry.unit.core.UnitRegistryController.lambda$registerUnitConfigAuthenticated$4(UnitRegistryController.java:551)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.InvalidStateException: Unit type of received message is unknown! Reject actions because the config seems to be broken.
	at org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.authenticatedAction(AuthenticatedServiceProcessor.java:121)
	... 5 common frames omitted
</pre>

It does not occur in the master branch because of some applied workarounds referred as issue related commits.

**Comment by pLeminoq** [comment]
I don't think this is an error and it does not mean that an incomplete unit config is transmitted.
Maybe this is a misconception because the AuthenticatedServiceProcessor is designed to work not only for registration processes but general authenticated actions. The important parts are the difference between the received message and the retrieved unit config.
<pre>
RECEIVE message = (RECEIVE) parseFrom.invoke(null, authenticatedValue.getValue());

// retrieve the unit config which is used to check for permissions 
UnitConfig unitConfig = configRetrieval.retrieve(message);
</pre>

The transmitted unit config for registry tasks is the message of type RECEIVE. This could also be
something else than a unit config, e.g. an action description. The config retrieval has the task to find a unit config containing the permissions needed to be allowed to do the requested action. For example for applying an action on a unit it should just retrieve the config of that unit using the given action description. In the case of a registry task this should be the unit config which is updated/removed.

But registration of a unit config is a special case because you cannot just take the permissions in this config. Otherwise anybody could register anything because he can set the permissions as he likes before registration. Thus the config retrieval has to look up other permissions. Normally the placement of a unit is defined and then the according location is retrieved. But currently the system can contain units without a placement e.g. users. So if no placement is defined the config retrieval tries to retrieve the root location. But what do we do if even the root location is not available. This can happen because we do not generate one on startup. And this is the special case this issue is about.

At the start of the mock registry a user is registered even before the root location is created. Therefore the config retrieval generates a unit config just containing a permission config which allows anything. The same happens again when the root location is registered. So this is needed to allow registering a root location and units without placements.

Therefore I would suggest removing the check because this unit config is not transmitted but only used to check permissions for the action.

**Comment by DivineThreepwood** [comment]
Outdated and properly solved.
